import 'package:flutter/material.dart';

Color defaultBlueColor0D = const Color(0xFF0D47A1);
Color defaultColorDC = const Color(0xFFDCE2FF);
Color defaultBlackColor00 = const Color(0xFF000000);
Color defaultWhiteColorFF = const Color(0xFFFFFFFF);
Color defaultColorE6 = const Color(0xFFE6F0FF);
Color defaultColor1E = const Color(0xFF1E1E1E);
Color defaultColor0D_50 = const Color(0xFF0D47A1).withOpacity(0.5);
Color defaultColorF9 = const Color(0xFFF9F9F9);
Color defaultRedColorFF = const Color(0xFFFF1921);
Color defaultColorBA_50 = const Color(0xFFBAC5FF).withOpacity(0.5);
Color defaultColor15_76 = const Color(0xFF1595EB).withOpacity(0.76);
Color defaultColorDD = const Color(0xFFDDE2FF);
Color defaultColorED = const Color(0xFFEDEFF7);
Color defaultColorD9 = const Color(0xFFD9D9D9);
Color defaultColor44 = const Color(0xFF444444);
Color defaultColorGrey = Colors.grey;
Color defaultColorB8_30 = const Color(0xFFB8D2FF).withOpacity(0.30);
Color defaultColorEC = const Color(0xFFECF2F7);